Add repository create method
AndcultureCode/AndcultureCode.CSharp.Sitefinity.Conductors pull request #3
Opened 2021-02-16 22:08 UTC by cspath1

Addresses Issue #2 

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)

2021-02-17 11:53 UTC, Stefanie899 requested changes
The most pressing change prior to approval is the addition of comments to the extension methods, in my opinion.

2021-02-17 11:53 UTC, Stefanie899 commented on src/AndcultureCode.CSharp.Sitefinity.Conductors/Extensions/DynamicContentExtensions.cs
> +        public static DynamicContent SetDataItemProperties<T>(this T item, PropertyInfo[] properties, string providerName) where T : SitefinityContent
I think we should add summary comments to the extension methods in this class describing what each of them do.

2021-02-17 11:53 UTC, Stefanie899 commented on src/AndcultureCode.CSharp.Sitefinity.Conductors/Extensions/DynamicContentExtensions.cs
> +            if (!property.PropertyType.IsSubclassOf(typeof(SitefinityContent)) &&
Minor: Persist the `IsSubclassOf` results in variables for readability, and so you don't have to write the same function call on line 65.

2021-02-17 11:53 UTC, Stefanie899 commented on src/AndcultureCode.CSharp.Sitefinity.Conductors/Extensions/DynamicContentExtensions.cs
> +            if (sitefinityType != null)
Invert the null to reduce nesting:

```
if (sitefinityType == null)
{
   return dataItem;
}
```

2021-02-17 11:53 UTC, Stefanie899 commented on src/AndcultureCode.CSharp.Sitefinity.Conductors/Domain/DynamicContentRepositoryConductor.cs
> +            // TODO: shouldn't this be done in the constructor?
Minor: Remove or resolve `TODO`. In this case, I don't think it should be done in the constructor as it's possible the `DefaultProviderName` is changed by the user prior to the call but after the instantiation of the conductor, in order to retrieve from a different provider.

2021-02-17 12:50 UTC, Stefanie899 approved these changes
Looks good now! Thanks!

2021-02-17 14:06 UTC, KevinBusch approved these changes

2021-02-17 14:33 UTC, KevinBusch approved these changes

2021-02-17 14:47 UTC, KevinBusch approved these changes

2021-02-17 14:47 UTC, merged

2021-05-17 12:17 UTC, brandongregoryscott commented
@all-contributors add @cspath1 for code

2021-05-17 12:18 UTC, brandongregoryscott commented
@all-contributors add @Stefanie899 for review